//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OWBS_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetectData
    {
        public string ID { get; set; }
        public string StationFK { get; set; }
        public System.DateTime RecordDT { get; set; }
        public string RecordFile { get; set; }
        public int RecordLen { get; set; }
        public string Data_json { get; set; }
        public string Output1_mp4 { get; set; }
        public string Output2_mp4 { get; set; }
        public string Output3_mp4 { get; set; }
        public string Output4_mp4 { get; set; }
        public string Output5_mp4 { get; set; }
        public string Sample_xlsx { get; set; }
        public string Stage { get; set; }
        public int Mode { get; set; }
        public int Dist { get; set; }
        public string Tls_1_mp4 { get; set; }
        public string Tls_2_mp4 { get; set; }
        public int Percentage { get; set; }
        public Nullable<System.DateTime> BgnDT { get; set; }
        public Nullable<System.DateTime> EndDT { get; set; }
        public long SeqNo { get; set; }
        public string IS_CANCEL { get; set; }
    }
}
